fix: Remove time after serial
ubuntu-bartenders/ubuntu-old-fashioned pull request #101
Opened 2024-08-21 17:02 UTC by JessicaJang

Serial string contains time which
doesn't look like what we need to keep
as serial (ex. 20240820.2151).

Remove time string followed by serial so
image can have only `serial` info.

2024-08-22 17:09 UTC, rthill91 approved these changes

2024-09-03 16:18 UTC, codyshepherd requested changes
How does this benefit the tool? Isn't it more helpful to have the time suffix, since old-fashioned is used primarily for building test images? Isn't it helpful to have the time info to differentiate one image built on a given day from another? I don't see the value add of this change.

2024-09-03 21:52 UTC, JessicaJang commented
@codyshepherd we use this tool for building and testing image locally. My intention of this fix was there was a conversation about checking build_info file itself (not implemented yet) and I thought it would be nice if we sync with our regular images which only have serial and not the time.

Regarding time part, I don't think time is also used in anywhere either.

But this is more suggestion than bug or fix.

2024-09-10 23:12 UTC, JessicaJang commented
@codyshepherd it would more make sense to keep suffix if that's part of reason. I will reject this MP since there is no need to fix this. Thanks! :+1:

2024-09-10 23:13 UTC, closed without merging