(feat) Migrate to Focal
ubuntu-bartenders/ubuntu-old-fashioned pull request #77
Opened 2022-02-25 18:24 UTC by j5awry

20220222, Lauchpad Builders migrated to Focal for the underlying VMs.
This aligns ubuntu-bartender's automated support, and updates
old-fashioned's statements on what Ubuntu versions are supported.

also adds the ability to configure GCE host vms in case of future
changes or wishing to do work on a specific image. This was supported in
other providers already

2022-02-25 18:36 UTC, j5awry commented
I tested this by

1. running an AWS build with defaults
2. running an AWS `--aws-arm-build` 
3. running a GCE build with defaults
4. running a GCE build with a unique image
5. running an Azure build (i have a local problem, unrelated to this, but it is why i added the RG loop)
6. running a multipass build

everything was fine, outside an unrelated issue I am having with  Azure. the builds succeeded on Focal

one _big_ caveat to all of this. Launchpad builders use the LTS kernel _not_ the rolling kernel. That's going to be a delta when building on the clouds. on `multipass` the image will use the LTS kernel. Considering CPC does not publish LTS kernel based images for the clouds, Bartenders may wish to examine installing the LTS kernel as part of the bootstrapping phase.

2022-02-28 06:12 UTC, ikapelyukhin commented on scripts/ubuntu-bartender/ubuntu-bartender
> +GCE_IMAGE="ubuntu-2004-lts"
That's image family, though (as compared to an image with a serial).

2022-02-28 06:41 UTC, toabctl requested changes

2022-02-28 06:41 UTC, toabctl commented on scripts/ubuntu-bartender/azure-provider
> +  # there can be a lag in resource group creation, which leads to VMs never getting made
please use something like `az group wait --created  --resource-group MyResourceGroup` (see https://docs.microsoft.com/en-us/cli/azure/group?view=azure-cli-latest#az-group-wait-examples )

2022-02-28 06:41 UTC, toabctl commented on scripts/ubuntu-bartender/ubuntu-bartender
> +MULTIPASS_IMAGE=daily:f # daily image of bionic
the comment is still wrong (but I would prefer to just replace `f` with the full name (`focal`) and drop the comment

2022-02-28 06:41 UTC, toabctl commented on scripts/ubuntu-bartender/ubuntu-bartender
> +AZURE_URN="Canonical:0001-com-ubuntu-server-focal-daily:20_04-daily-lts-gen2:latest"
is that correct? if so, why do we have `daily` 2x in the name?

2022-03-01 12:16 UTC, philroche approved these changes

2022-09-30 17:22 UTC, j5awry commented
Something has gone sideways on this branch, somewhere, because it's failing to work on Focal based hosts. need to do some more digging and figure out what has happened :/

2022-12-06 15:43 UTC, toabctl commented
@j5awry should we create a issue so we can track working on this soon?

2022-12-06 16:54 UTC, j5awry commented
made #80 . light on details, but at least captures the gist. I've also moved this to Draft, with some expectation that we do a "second take" with a new branch...but we don't lose the original attempt

2023-02-14 19:22 UTC, rpocase commented
@j5awry Should we just close and open an internal issue? As long as the PR isn't deleted than latest commit history is kept.

2023-02-16 13:15 UTC, j5awry commented
I can close, if we'd rather do that to keep things clean. 

we can open an internal ticket to mirror the public one (#80 ) if you want, but we should still work publicly on it. i dislike having bugs in 2 locations (more like 4 with our team)

2023-02-16 13:15 UTC, closed without merging

2023-02-16 15:57 UTC, rpocase commented
Agreed on keeping work publicly. I tend to prefer duplicating since it seems like if its not internally tracked its won't be prioritized and fixed, but I'm not hard stuck on that.